API_ID: 24119691
API_HASH: ac22dd1322c2a6c3bb2dce7450de15b4
BOT_TOKEN: 5676863873:AAEqv0tdhMgyw4YTw0O31d2oqSxJkYL269o


MONGO_URL: mongodb+srv://checker:checker@cluster0.qxdm0fi.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-18451.c82.us-east-1-2.ec2.cloud.redislabs.com:18451
REDIS_PORT: 18451
REDIS_PASS: 5WJtBM8EXY7QTcAywq7gLMfrTatNuTy3

SESSION_API_ID: 24119691
SESSION_API_HASH: ac22dd1322c2a6c3bb2dce7450de15b4
SESSION_STRING: BQAOO1TY0CeyUeeSBeSbOgGk1LBkBY0b4N7LlpVb4MISWVjnYZOcWIvlRl8BW4xHM2xOh3LIqAPSsDpL1cOChkHnBxul5Z6EEd5RSCAPfbtgjAJj9JezxxpNvRiGSJbDQOmIEgHyyfFIxypuqhndsfVzbiFdqirsvOuCGPeUqsU7in-KB-pfUf0x_ZLFh9Y8Kwf0X09kOj58yAOEGJEw1K1IhfIJL1q4maSnTMs-i-x3BXmK_GUWl5HzvtvderkOxCVoi0aycY_hycr1n2lOQ4_nl6MvVdcZ0ssDiNxEM68pCqmyyXq9KfLSN9Q3f9FZMBWQE8tlIi0GUs26ymPRKtenAAAAAWYhsCgA

ADMINS: 
  - 5721949879

OWNER: 5721949879

BOT_PIC: https://telegra.ph/file/4664bf1e48d763a5cab81.jpg
OWNER_PIC: https://telegra.ph/file/4664bf1e48d763a5cab81.jpg

SUPPORT_CHAT: CHATTING_HUB_69 
# LOG_CHAT: 
LOG_CHAT: -1001642871624



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

