API_ID: 24119691
API_HASH: ac22dd1322c2a6c3bb2dce7450de15b4
BOT_TOKEN: 5676863873:AAEqv0tdhMgyw4YTw0O31d2oqSxJkYL269o


MONGO_URL: mongodb+srv://checker:checker@cluster0.qxdm0fi.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-18451.c82.us-east-1-2.ec2.cloud.redislabs.com:18451
REDIS_PORT: 18451
REDIS_PASS: 5WJtBM8EXY7QTcAywq7gLMfrTatNuTy3

SESSION_API_ID: 24119691
SESSION_API_HASH: ac22dd1322c2a6c3bb2dce7450de15b4
SESSION_STRING: 1BVtsOH4Bu1yn13EPSXRx5beNWIFxyVrwWNHUxF6dPLfuHDVQBbwnbibpghJ1PAzLYcYk6GJptKDECL72F15qAZoC6jqUQBHv87glKwr7yu8y6oKJL0opTxbktkxQlqKzHoaSrf0FbNJsIM2WEJUpYm03pvuuoOvmwJ7mQXsLlUd4u5SYEvWpNVvhoirng3iGqW2MsM-jh_5Bx3D7DJgXhBCgSjh5l2rxZdKhnS7eLajjPuPvdXVStZ_R1oPKq5o_c5w2v7eUcIpaluHgla0q9KDudHbkzs1DM24PYT9LVO5LWiiO_5FRh6b-_0ITXiCW7kHhFkqKEQUyfVZ8rLl7zSUHaNCvqwo=

ADMINS: 
  - 5721949879

OWNER: 5721949879

BOT_PIC: https://telegra.ph/file/4664bf1e48d763a5cab81.jpg
OWNER_PIC: https://telegra.ph/file/4664bf1e48d763a5cab81.jpg

SUPPORT_CHAT: CHATTING_HUB_69 
# LOG_CHAT: 
LOG_CHAT: -1001642871624



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

