API_ID: 24119691
API_HASH: ac22dd1322c2a6c3bb2dce7450de15b4
BOT_TOKEN: 5676863873:AAEqv0tdhMgyw4YTw0O31d2oqSxJkYL269o


MONGO_URL: 
REDIS_URI: redis-18451.c82.us-east-1-2.ec2.cloud.redislabs.com:18451
REDIS_PORT: 18451
REDIS_PASS: 5WJtBM8EXY7QTcAywq7gLMfrTatNuTy3

SESSION_API_ID: 
SESSION_API_HASH: 
SESSION_STRING: 

ADMINS: 
  - 1317173146

OWNER: 1317173146

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT: roldexversechats 
# LOG_CHAT: 
LOG_CHAT: 



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

